name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11.9
  # REGISTRY: region-docker.pkg.dev/project-id ## in case of deploy to GCP Artifact
  REGISTRY: docker.io
  IMAGE_NAME: klm-note-api
  DOCKER_USERNAME: ahmedsoli101
jobs:
  lint:
    name: Linting and Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Python Environment Setup
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ env.PYTHON_VERSION}}
          cache-key-suffix: 'lint'

      - name: Check Code Formmating with Black
        run: |
          black --check --diff .

      - name: Lint Code with Flake8
        run: |
          flake8 . --count --show-source --statistics --exclude=.venv
        continue-on-error: true

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python Environemnt
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache-key-suffix: 'test-${{env.PYTHON_VERSION}}'
      - name: Activate PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c 'select 1' || sleep 6
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.DB_PASSWORD }}'"
          sudo -u postgres psql -c "create database notes_db"

      - name: Run Tests
        env:
          DB_URL: ${{secrets.DB_URL}}
        run: |
          python3 -m pytest
  # terraform-validate:
  #   runs-on: ubuntu-latest
  #   needs: [lint, tests]
  #   steps:
  #     - uses: actions/checkout@v3
     
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.6.0
     
  #     - name: Terraform Format Check
  #       run: terraform fmt -check -recursive terraform/
     
  #     - name: Terraform Validate
  #       run: |
  #         cd terraform/
  #         terraform init -backend=false
  #         terraform validate
     
  #     - name: Run tfsec (Security Scan)
  #       uses: aquasecurity/tfsec-action@v1.0.0
  #       with:
  #         working_directory: terraform/

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    # needs: [lint, tests, terraform-validate]
    needs: [lint, tests]
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python Environemnt
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache-key-suffix: 'build'

      - name: Get Metadata of Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Artifact Registry path structure in case of DCP
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=KLM note-api application
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # WIF for authentication in case of GCP Artifact
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
      - name: Build Summary
        run: |
          echo "Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "Image Tags: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "Image Digest: ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
          echo "Platforms: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY

  # deploy-infrastructure:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   env:
  #     PROJECT_ID: ID
  #     REGION: eu-central
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write' 

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2

  #     - name: Authenticate to GCP
  #       uses: google-github-actions/auth@v1
  #       with:
  #         # Replace with your IAM Workload Identity Federation Provider config
  #         workload_identity_provider: '****github-provider'
  #         service_account: cr-deployer-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

  #     - name: Terraform Plan
  #       run: |
  #         cd terraform/
  #         terraform init
  #         terraform plan \
  #           -var="project_id=${{ env.PROJECT_ID }}" \
  #           -var="region=${{ env.REGION }}" \
  #           -var="image_url=${{ needs.build.outputs.image-digest }}" \
  #           -out=tfplan
          
  #     - name: Terraform Apply
  #       run: |
  #         cd terraform/
  #         terraform apply tfplan
  
  # deploy-application:
  #   needs: deploy-infrastructure
  #   runs-on: ubuntu-latest
  #   env:
  #     PROJECT_ID: ID
  #     SERVICE_NAME: SA
  #     REGION: eu-central1
  #     SECRET_NAME: DB_URL_SECRET

  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'

  #   steps:
  #     - name: Authenticate to GCP using WIF
  #       uses: google-github-actions/auth@v1
  #       with:
  #         workload_identity_provider: **github-provider 
  #         service_account: cr-deployer-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          
  #     - name: Deploy to Cloud Run
  #       run: |
  #         gcloud run deploy ${{ env.SERVICE_NAME }} \
  #         --region=${{ env.REGION }} \
  #         --platform=managed \
  #         --image ${{ needs.build.outputs.image-digest }} \
  #         --set-secrets=${{ env.SECRET_NAME }}=${{ env.SECRET_NAME }}:latest \
  #         --set-env-vars=FLASK_APP=run.py \
  # integration-tests:
  #   needs: deploy-application
  #   runs-on: ubuntu-latest
  #   env:
  #     SERVICE_NAME: SA
  #     REGION: eu-central
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run integration tests
  #       run: |
  #         SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
  #         --region=${{ env. REGION }} \
  #         --format="value(status.url)")
  #         python3 -m pytest tests/integration/ --api-ur1=$SERVICE_URL