name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11.9
jobs:
  lint:
    name: Linting and Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Python Environment Setup
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ env.PYTHON_VERSION}}
          cache-key-suffix: 'lint'

      - name: Check Code Formmating with Black
        run: |
          black --check --diff .

      - name: Lint Code with Flake8
        run: |
          flake8 . --count --show-source --statistics --exclude=.venv
        continue-on-error: true

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python Environemnt
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache-key-suffix: 'test-${{env.PYTHON_VERSION}}'
      - name: Activate PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c 'select 1' || sleep 6
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.DB_PASSWORD }}'"
          sudo -u postgres psql -c "create database notes_db"

      - name: Run Tests
        env:
          DB_URL: ${{secrets.DB_URL}}
        run: |
          python3 -m pytest
